### PR TITLE
Set Seed in Shiny App

### PR DESCRIPTION
**Pull request by kylehamilton**
Adds the ability to set the seed value for simulations in the shiny app as requested in issue #27

### CODE REVIEW

**Comment by arcaldwell49** [comment]
Very good work Kyle. I will test this out over the weekend and hopefully merge with the base branch soon.

**Comment by Lakens** [comment]
Cool, thanks! I've created a seperate branch for the R package: https://github.com/Lakens/ANOVApower We will integrate your contribution, update the app with the new code. Some of us are a bit busy completing a PhD, but within a month we will be ready with this. Thanks for the contribution.

**Comment by kylehamilton** [comment]
No worries if you post more issues in either of the repos I'll try and take a crack at them. It's a welcome distraction from my candidacy paper.

**Comment by arcaldwell49** [comment]
A new update to the Shiny app, incorporating the new ANOVApower functions, now allows for setting the seed.

**Pull request closed without merging**
